// Generated by ts-to-zod
import { z } from "zod";

export const commentSchema = z.object({
  id: z.number(),
  parent_id: z.number().nullable(),
  display_name: z.string(),
  text: z.string(),
  created_at: z.string(),
});

export const postSchema = z.object({
  post_url: z.string(),
  title: z.string(),
  created_at: z.string(),
  num_hugs: z.number(),
  patient_description: z.string(),
  assessment: z.string(),
  question: z.string(),
  comments: z.record(commentSchema),
});
